server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://db:3306/shipmentdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: my_jwt_secret_key
  expiration: 86400000
